// src/js/data.js

export const productsData = {
    // ================= KHỐI 1: CÁC SẢN PHẨM TRÊN TRANG CHỦ (INDEX) =================
    "moya-combo": {
        title: "Combo Phòng Ngủ TLU MOYA (Giường Có Hộc & Ổ Điện Và Tủ...)",
        sku: "MSET_MOYA_BED",
        discount: "-35%",
        currentPrice: "15,490,000đ",
        oldPrice: "23,980,000đ",
        colorName: "Vàng Sồi Phối Trắng",
        size: "Giường W1600mm x L2000mm có hộc thông minh",
        materials: ["Gỗ công nghiệp PB chuẩn CARB-P2", "Bề mặt phủ Melamine chống trầy chống ẩm"],
        descTitle: "Combo MOYA - Giải Pháp Không Gian Phòng Ngủ Hiện Đại",
        descText: "Thiết kế giường ngủ tích hợp ổ cắm sạc điện thông minh đầu giường và hộc kéo chứa đồ ẩn dưới gầm tối ưu không gian.",
        mainImg: "/src/images/index/Link → Picture → Combo Phòng Ngủ MOHO MOVA (Giường Có Hộc & Ổ Điện Và Tủ Áo).png",
        thumbs: ["/src/images/index/Link → Picture → Combo Phòng Ngủ MOHO MOVA (Giường Có Hộc & Ổ Điện Và Tủ Áo).png"],
        descImg: "/src/images/index/Link → Picture → Combo Phòng Ngủ MOHO MOVA (Giường Có Hộc & Ổ Điện Và Tủ Áo).png"
    },
    "sofa-riga": {
        title: "Ghế Sofa Da TLU RIGA 2m",
        sku: "MFSACF200_RIGA",
        discount: "-37%",
        currentPrice: "11,490,000đ",
        oldPrice: "18,290,000đ",
        colorName: "Trắng Kem",
        size: "W2000mm x D850mm x H800mm",
        materials: ["Da công nghiệp Hàn Quốc cao cấp, dễ dàng vệ sinh", "Khung gỗ tự nhiên kết hợp đệm mút lò xo túi"],
        descTitle: "Sofa Da RIGA - Đẳng Cấp Sang Trọng Lịch Lãm",
        descText: "Kiểu dáng thanh lịch mang phong cách Bắc Âu hiện đại, chất liệu da êm ái chống thấm nước tối ưu.",
        mainImg: "/src/images/index/Link → Picture → Ghế Sofa Da MOHO RIGA 2m.png",
        thumbs: ["/src/images/index/Link → Picture → Ghế Sofa Da MOHO RIGA 2m.png"],
        descImg: "/src/images/index/Link → Picture → Ghế Sofa Da MOHO RIGA 2m.png"
    },
    "vline-601": {
        title: "Giường Ngủ Gỗ TLU VLINE 601 Nhiều Kích Thước",
        sku: "MBDVLI601_OAK",
        discount: "-21%",
        currentPrice: "6,490,000đ",
        oldPrice: "7,990,000đ",
        colorName: "Màu gỗ tự nhiên",
        size: "W1600mm x L2000mm x H900mm",
        materials: ["Gỗ tràm tự nhiên nguyên khối vạt giường thanh phẳng chắc chắn", "Veneer sồi cao cấp"],
        descTitle: "Giường Ngủ VLINE - Nét Đẹp Đơn Giản, Tinh Tế",
        descText: "Thiết kế gầm cao thoáng đãng, các góc cạnh bo tròn an toàn, mang đậm phong cách nội thất đương đại.",
        mainImg: "/src/images/index/Link → Picture → Giường Ngủ Gỗ MOHO VLINE 601 Nhiều Kích Thước.png",
        thumbs: ["/src/images/index/Link → Picture → Giường Ngủ Gỗ MOHO VLINE 601 Nhiều Kích Thước.png"],
        descImg: "/src/images/index/Link → Picture → Giường Ngủ Gỗ MOHO VLINE 601 Nhiều Kích Thước.png"
    },
    "homro-301": {
        title: "Giường Ngủ Gỗ Tự Nhiên TLU HOMRO 301",
        sku: "MBDHOM301_NAT",
        discount: "-14%",
        currentPrice: "8,490,000đ",
        oldPrice: "9,990,000đ",
        colorName: "Vàng gỗ tự nhiên",
        size: "W1800mm x L2000mm",
        materials: ["100% Gỗ cao su tự nhiên sơn phủ hệ nước chống mốc mối mọt"],
        descTitle: "Giường HOMRO 301 - Kết Cấu Chắc Chắn Vượt Thời Gian",
        descText: "Hệ vạt tấm phẳng chịu tải trọng siêu lớn, kết cấu mộng gỗ khít khao không gây ra tiếng động khi trở mình.",
        mainImg: "/src/images/index/Link → Picture → Giường Ngủ Gỗ Tự Nhiên MOHO HOBRO 301.png",
        thumbs: ["/src/images/index/Link → Picture → Giường Ngủ Gỗ Tự Nhiên MOHO HOBRO 301.png"],
        descImg: "/src/images/index/Link → Picture → Giường Ngủ Gỗ Tự Nhiên MOHO HOBRO 301.png"
    },
    "dalumd-301": {
        title: "Giường Ngủ Gỗ Tràm TLU DALUMD 301 Ver 2",
        sku: "MBDDAL301_V2",
        discount: "-18%",
        currentPrice: "9,490,000đ",
        oldPrice: "10,990,000đ",
        colorName: "Nâu trầm hạnh nhân",
        size: "W1800mm x L2000mm",
        materials: ["Gỗ tràm tự nhiên xẻ sấy tiêu chuẩn xuất khẩu"],
        descTitle: "Giường DALUMD Ver 2 - Bản Tình Ca Mộc Mạc Từ Thiên Nhiên",
        descText: "Sở hữu những thớ vân gỗ uốn lượn tự nhiên độc bản, mang lại cảm giác ấm cúng, dễ chịu cho phòng ngủ.",
        mainImg: "/src/images/index/Link → Picture → Giường Ngủ Gỗ Tràm MOHO DALUMD 301 Ver 2 Màu Nâu Hạnh Nhân.png",
        thumbs: ["/src/images/index/Link → Picture → Giường Ngủ Gỗ Tràm MOHO DALUMD 301 Ver 2 Màu Nâu Hạnh Nhân.png"],
        descImg: "/src/images/index/Link → Picture → Giường Ngủ Gỗ Tràm MOHO DALUMD 301 Ver 2 Màu Nâu Hạnh Nhân.png"
    },
    "koster-combo": {
        title: "Full Combo Phòng Ngủ TLU KOSTER Màu Nâu",
        sku: "MSET_KOS_BROWN",
        discount: "-21%",
        currentPrice: "14,990,000đ",
        oldPrice: "18,970,000đ",
        colorName: "Nâu sẫm phối màu",
        size: "Giường ngủ 1m8 x 2m kèm hệ táp gỗ đầu giường đồng điệu",
        materials: ["Gỗ cao su tự nhiên", "MDF chống ẩm lõi mịn tiêu chuẩn châu Âu"],
        descTitle: "Full Combo KOSTER - Sự Đồng Bộ Tiết Kiệm Chi Phí",
        descText: "Giải pháp trọn gói thiết kế phòng ngủ giúp căn phòng đạt thẩm mỹ đồng điệu tối đa mà không tốn công phối đồ.",
        mainImg: "/src/images/index/Link → Picture → Full Combo Phòng Ngủ MOHO KOSTER Màu Nâu.png",
        thumbs: ["/src/images/index/Link → Picture → Full Combo Phòng Ngủ MOHO KOSTER Màu Nâu.png"],
        descImg: "/src/images/index/Link → Picture → Full Combo Phòng Ngủ MOHO KOSTER Màu Nâu.png"
    },
    "nem-signature": {
        title: "Nệm Lò Xo TLU Sleep Signature",
        sku: "MAT_SIG_30CM",
        discount: "-24%",
        currentPrice: "7,990,000đ",
        oldPrice: "10,490,000đ",
        colorName: "Trắng hoa văn thêu nổi",
        size: "W1800mm x L2000mm x H300mm",
        materials: ["Hệ lò xo túi liên kết chịu lực độc lập cao tần", "Vải gấm xốp kháng khuẩn nhập khẩu"],
        descTitle: "Sleep Signature - Trải Nghiệm Giấc Ngủ Khách Sạn 5 Sao",
        descText: "Độ dày ấn tượng 30cm nâng đỡ phân vùng cơ thể hoàn hảo, cô lập chuyển động giúp người nằm cạnh không bị thức giấc.",
        mainImg: "/src/images/index/Link → Picture → Nệm Lò Xo MOHO Sleep Signature.png",
        thumbs: ["/src/images/index/Link → Picture → Nệm Lò Xo MOHO Sleep Signature.png"],
        descImg: "/src/images/index/Link → Picture → Nệm Lò Xo MOHO Sleep Signature.png"
    },
    "kitchen-premium": {
        title: "HỆ TỦ BẾP TLU KITCHEN DÒNG PREMIUM",
        discount: "Premium",
        currentPrice: "Giá từ 45.000.000đ",
        mainImg: "/src/images/index/Link → Picture → HỆ TỦ BẾP MOHO KITCHEN DÒNG PREMIUM.png"
    },
    "kitchen-standard": {
        title: "HỆ TỦ BẾP TLU KITCHEN DÒNG STANDARD",
        discount: "Standard",
        currentPrice: "Giá từ 35.000.000đ",
        mainImg: "/src/images/index/Link → Picture → HỆ TỦ BẾP MOHO KITCHEN DÒNG STANDARD.png"
    },
    "kitchen-essential": {
        title: "HỆ TỦ BẾP TLU KITCHEN DÒNG ESSENTIAL",
        discount: "Essential",
        currentPrice: "Giá từ 30.000.000đ",
        mainImg: "/src/images/index/Link → Picture → HỆ TỦ BẾP MOHO KITCHEN DÒNG ESSENTIAL.png"
    },
    "kitchen-narvik": {
        title: "Hệ tủ bếp TLU Kitchen Premium Narvik",
        discount: "Narvik",
        currentPrice: "Liên hệ nhận tư vấn và thiết kế miễn phí",
        mainImg: "/src/images/index/Link → Picture → Hệ tủ bếp MOHO Kitchen Premium Narvik Nhiều Kích Thước.png"
    },

    // ================= KHỐI 2: DỮ LIỆU CŨ CỦA TRANG SẢN PHẨM TRÊN PRODUCTS (GIỮ NGUYÊN) =================
    "sofa-mochi": {
        title: "Ghế Sofa 1m8 TLU MOCHI",
        sku: "MFSACF608_N18",
        discount: "-29%",
        currentPrice: "9,990,000đ",
        oldPrice: "13,990,000đ",
        colorName: "Be",
        colors: ["#e6dfd1", "#4a7c49"],
        size: "W1800mm x D780mm x H733/411mm (Kích thước lọt lòng: W1600 mm)",
        materials: ["Vải: 100% polyester; trượt nước", "Chân gỗ cao su", "Khung gỗ tự nhiên"],
        descTitle: "Sofa MOCHI - Chiếc Kén Gói Trọn Bình Yên",
        descText: "Giữa nhịp sống nhiều áp lực, điều ta thật sự cần không chỉ là một chiếc sofa, mà là một nơi để thả lỏng... Sofa MOCHI ra đời từ chính nhu cầu đó.",
        mainImg: "/src/images/products/Link → Picture → Ghế Sofa 1m8 MOHO MOCHI.png",
        thumbs: ["/src/images/products/Link → Picture → Ghế Sofa 1m8 MOHO MOCHI.png"],
        descImg: "/src/images/products/Link → Picture → Ghế Sofa 1m8 MOHO MOCHI.png"
    },
    "armchair-olly": {
        title: "Ghế Armchair Thư Giãn Kèm Đôn TLU OLLY",
        sku: "MFSACF902_OLLY",
        discount: "-41%",
        currentPrice: "10,990,000đ",
        oldPrice: "18,480,000đ",
        colorName: "Xanh rêu",
        colors: ["#3b5323", "#e8dcc4"],
        size: "W850mm x D900mm x H950mm",
        materials: ["Vải bọc nỉ cao cấp", "Khung thép chịu lực", "Đôn gác chân thư giãn đi kèm"],
        descTitle: "Armchair OLLY - Nâng Niu Phút Giây Thư Giãn",
        descText: "Thiết kế ôm trọn cơ thể kết hợp cùng đôn gác chân êm ái, Ghế Armchair OLLY là người bạn đồng hành hoàn hảo cho những buổi đọc sách hay xem phim cuối tuần.",
        mainImg: "/src/images/products/Link → Picture → Ghế Armchair Thư Giãn Kèm Đôn MOHO OLLY.png",
        thumbs: ["/src/images/products/Link → Picture → Ghế Armchair Thư Giãn Kèm Đôn MOHO OLLY.png"],
        descImg: "/src/images/products/Link → Picture → Ghế Armchair Thư Giãn Kèm Đôn MOHO OLLY.png"
    },
    "giuong-blink": {
        title: "Giường Ngủ Bọc Da Cao Cấp Hiện Đại TLU BLINK",
        sku: "MBDBLI18_LEATHER",
        discount: "-9%",
        currentPrice: "15,990,000đ",
        oldPrice: "17,490,000đ",
        colorName: "Nâu Đậm",
        colors: ["#5c4033"],
        size: "W1800mm x L2000mm x H1050mm",
        materials: ["Da Microfiber cao cấp chống trầy xước", "Khung hợp kim siêu chịu lực"],
        descTitle: "Giường TLU BLINK - Đẳng Cấp Thượng Lưu Hiện Đại",
        descText: "Sự kết hợp hoàn hảo giữa chất liệu da cao cấp và các đường may cơ học tỉ mỉ mang lại diện mạo quyền lực, đẳng cấp cho căn phòng.",
        mainImg: "/src/images/products/Link → Picture → Giường Ngủ Bọc Da Cao Cấp Hiện Đại MOHO BLINK.png",
        thumbs: ["/src/images/products/Link → Picture → Giường Ngủ Bọc Da Cao Cấp Hiện Đại MOHO BLINK.png"],
        descImg: "/src/images/products/Link → Picture → Giường Ngủ Bọc Da Cao Cấp Hiện Đại MOHO BLINK.png"
    },
    "tu-ao-astro": {
        title: "Combo Tủ Quần Áo Cánh Kính TLU ASTRO - Nhiều kích thước",
        sku: "MWRWAR120_GLASS",
        discount: "-15%",
        currentPrice: "23,490,000đ",
        oldPrice: "27,480,000đ",
        colorName: "Vàng Gỗ",
        colors: ["#d2b48c"],
        size: "W1200mm x D600mm x H2200mm",
        materials: ["Cánh kính cường lực cao cấp khung nhôm sơn tĩnh điện", "Gỗ MDF chống ẩm phủ Melamine"],
        descTitle: "Tủ Áo ASTRO - Không Gian Trưng Bày Đỉnh Cao",
        descText: "Hệ thống cánh kính trong suốt kết hợp đèn LED chạy ngầm biến tủ quần áo của bạn thành một showroom trưng bày thời trang thu nhỏ đầy cuốn hút.",
        mainImg: "/src/images/products/Link → Picture → Combo Tủ Quần Áo Cánh Kính MOHO ASTRO - Nhiều kích thước.png",
        thumbs: ["/src/images/products/Link → Picture → Combo Tủ Quần Áo Cánh Kính MOHO ASTRO - Nhiều kích thước.png"],
        descImg: "/src/images/products/Link → Picture → Combo Tủ Quần Áo Cánh Kính MOHO ASTRO - Nhiều kích thước.png"
    },
    "tu-don-astro": {
        title: "Tủ Quần Áo Cánh Kính 60cm TLU ASTRO - Nhiều mẫu tủ đơn",
        sku: "MWRWAR060_SINGLE",
        discount: "-10%",
        currentPrice: "9,490,000đ",
        oldPrice: "10,490,000đ",
        colorName: "Vàng Gỗ",
        colors: ["#d2b48c"],
        size: "W600mm x D600mm x H2200mm",
        materials: ["Kính cường lực mờ chống bám vân tay", "Khung nhôm định hình cao cấp"],
        descTitle: "Tủ Đơn ASTRO - Giải Pháp Thiết Kế Cho Không Gian Nhỏ",
        descText: "Kích thước 60cm nhỏ gọn, tinh tế, dễ dàng ghép nối thêm các module tủ khác hoặc đặt vừa vặn vào các góc hẹp.",
        mainImg: "/src/images/products/Link → Picture → Tủ Quần Áo Cánh Kính 60cm MOHO ASTRO - Nhiều mẫu tủ đơn.png",
        thumbs: ["/src/images/products/Link → Picture → Tủ Quần Áo Cánh Kính 60cm MOHO ASTRO - Nhiều mẫu tủ đơn.png"],
        descImg: "/src/images/products/Link → Picture → Tủ Quần Áo Cánh Kính 60cm MOHO ASTRO - Nhiều mẫu tủ đơn.png"
    },
    "tu-dau-giuong": {
        title: "Tủ Đầu Giường VIENNA (Màu gỗ phối trắng)",
        sku: "MNTST050_VIENNA",
        discount: "-11%",
        currentPrice: "1,690,000đ",
        oldPrice: "1,890,000đ",
        colorName: "Trắng Phối Gỗ",
        colors: ["#f5f5f5"],
        size: "W500mm x D400mm x H450mm",
        materials: ["Gỗ công nghiệp đạt chuẩn CARB-P2 an toàn cho sức khỏe", "Chân sắt sơn tĩnh điện hình học"],
        descTitle: "Tủ Đầu Giường VIENNA - Tối Giản, Tiện Lợi Và Tinh Tế",
        descText: "Thiết kế hộc kéo mượt mà, màu sắc nhã nhặn tạo điểm nhấn decor hoàn hảo cho khu vực đầu giường.",
        mainImg: "/src/images/products/Link → Picture → Tủ Đầu Giường VIENNA (Màu gỗ phối trắng).png",
        thumbs: ["/src/images/products/Link → Picture → Tủ Đầu Giường VIENNA (Màu gỗ phối trắng).png"],
        descImg: "/src/images/products/Link → Picture → Tủ Đầu Giường VIENNA (Màu gỗ phối trắng).png"
    },
    "nem-balance": {
        title: "Nệm Foam TLU Sleep Balance",
        sku: "MATBAL18_FOAM",
        discount: "-11%",
        currentPrice: "7,990,000đ",
        oldPrice: "8,990,000đ",
        colorName: "Trắng Ghi",
        colors: [],
        size: "W1800mm x L2000mm x H200mm",
        materials: ["Memory Foam đàn hồi phân vùng", "Vỏ nệm sợi tre sinh học kháng khuẩn"],
        descTitle: "TLU Sleep Balance - Công Nghệ Nâng Đỡ Trạng Thái Cân Bằng",
        descText: "Hệ thống foam giải tỏa áp lực cột sống thông minh giúp bạn đi vào giấc ngủ nhanh hơn, giảm hẳn ê mỏi khi thức dậy.",
        mainImg: "/src/images/products/Link → Picture → Nệm Foam Moho Sleep Balance.png",
        thumbs: ["/src/images/products/Link → Picture → Nệm Foam Moho Sleep Balance.png"],
        descImg: "/src/images/products/Link → Picture → Nệm Foam Moho Sleep Balance.png"
    },
    "tu-astro-1m2": {
        title: "Tủ Quần Áo Cánh Kính Cao Cấp 1m2 TLU ASTRO",
        sku: "MWRWAR120_MID",
        discount: "-12%",
        currentPrice: "14,990,000đ",
        oldPrice: "16,990,000đ",
        colorName: "Vàng Gỗ",
        colors: ["#d2b48c"],
        size: "W1200mm x D600mm x H2200mm",
        materials: ["Kính cường lực màu trà chống lóa", "Thùng gỗ PB lõi xanh chống ẩm mốc"],
        descTitle: "ASTRO 1m2 - Sự Lựa Chọn Tối Ưu Cho Căn Hộ Hiện Đại",
        descText: "Sức chứa lớn với kết cấu chia ngăn khoa học, tối ưu diện tích phòng ngủ Master của các căn hộ chung cư.",
        mainImg: "/src/images/products/Link → Picture → Tủ Quần Áo Cánh Kính Cao Cấp 1m2 MOHO ASTRO.png",
        thumbs: ["/src/images/products/Link → Picture → Tủ Quần Áo Cánh Kính Cao Cấp 1m2 MOHO ASTRO.png"],
        descImg: "/src/images/products/Link → Picture → Tủ Quần Áo Cánh Kính Cao Cấp 1m2 MOHO ASTRO.png"
    },
    "tu-vline-v3": {
        title: "Combo Tủ Quần Áo VLINE V3",
        sku: "MWRVLI160_V3",
        discount: "-17%",
        currentPrice: "17,490,000đ",
        oldPrice: "20,980,000đ",
        colorName: "Nâu Gỗ Đậm",
        colors: ["#5c4033", "#d2b48c"],
        size: "W1600mm x D600mm x H2000mm",
        materials: ["Gỗ tràm tự nhiên phối Veneer sồi cao cấp", "Ray trượt hộc kéo giảm chấn Ivan"],
        descTitle: "VLINE V3 - Tôn Vinh Đường Nét Nội Thất Việt",
        descText: "Sự kết hợp tinh tế giữa vẻ đẹp truyền thống và công năng hiện đại, tạo nên giải pháp lưu trữ đồ đạc gọn gàng, bề thế.",
        mainImg: "/src/images/products/Link → Picture → Combo Tủ Quần Áo VLINE V3.png",
        thumbs: ["/src/images/products/Link → Picture → Combo Tủ Quần Áo VLINE V3.png"],
        descImg: "/src/images/products/Link → Picture → Combo Tủ Quần Áo VLINE V3.png"
    },
    "tu-don-vline": {
        title: "Tủ Quần Áo Đơn VLINE V3 - Các mẫu Tủ Đơn 60cm",
        sku: "MWRVLI060_V3",
        discount: "-11%",
        currentPrice: "7,990,000đ",
        oldPrice: "8,990,000đ",
        colorName: "Nâu Gỗ Đậm",
        colors: ["#5c4033", "#d2b48c"],
        size: "W600mm x D600mm x H2000mm",
        materials: ["Gỗ tràm tự nhiên đạt chuẩn xuất khẩu khắt khe", "Sơn phủ bảo vệ chống cong vênh mối mọt"],
        descTitle: "Tủ Đơn VLINE 60cm - Linh Hoạt Mọi Góc Nhìn",
        descText: "Mẫu tủ đơn linh hoạt, giải quyết bài toán lưu trữ quần áo phụ trợ hoặc tận dụng không gian hành lang hẹp.",
        mainImg: "/src/images/products/Link → Picture → Tủ Quần Áo Đơn VLINE V3 - Các mẫu Tủ Đơn 60cm.png",
        thumbs: ["/src/images/products/Link → Picture → Tủ Quần Áo Đơn VLINE V3 - Các mẫu Tủ Đơn 60cm.png"],
        descImg: "/src/images/products/Link → Picture → Tủ Quần Áo Đơn VLINE V3 - Các mẫu Tủ Đơn 60cm.png"
    },
    "tu-2-canh": {
        title: "Tủ Quần Áo 2 Cánh VLINE V3",
        sku: "MWRVLI120_V3",
        discount: "-13%",
        currentPrice: "10,490,000đ",
        oldPrice: "11,990,000đ",
        colorName: "Nâu Gỗ Đậm",
        colors: ["#5c4033", "#d2b48c"],
        size: "W1200mm x D600mm x H2000mm",
        materials: ["Khung gỗ tràm chắc chắn", "Tay nắm móc âm thẩm mỹ hiện đại"],
        descTitle: "VLINE V3 2 Cánh - Sự Tiện Nghi Cho Phòng Ngủ",
        descText: "Lòng tủ sâu tissue chuẩn treo quần áo thoải mái.",
        mainImg: "/src/images/products/Link → Picture → Tủ Quần Áo 2 Cánh VLINE V3.png",
        thumbs: ["/src/images/products/Link → Picture → Tủ Quần Áo 2 Cánh VLINE V3.png"],
        descImg: "/src/images/products/Link → Picture → Tủ Quần Áo 2 Cánh VLINE V3.png"
    },
    "dalumd-living": {
        title: "Bộ Nội Thất Phòng Khách TLU DALUMD",
        sku: "MSET_DALUMD_LIVING",
        discount: "-39%",
        currentPrice: "13,490,000đ",
        oldPrice: "22,070,000đ",
        colorName: "Nâu Gỗ Óc Chó",
        colors: ["#5c4033"],
        size: "Gồm 1 Kệ Tivi bệ bệt và 1 Bàn Trà hình chữ nhật",
        materials: ["Gỗ tự nhiên bền bỉ", "Bề mặt phủ Veneer Óc Chó nhập khẩu cao cấp"],
        descTitle: "Combo Phòng Khách DALUMD - Đẳng Cấp Không Gian Sống",
        descText: "Tông màu nâu óc chó quý phái kết hợp đường vân gỗ uốn lượn sắc nét.",
        mainImg: "/src/images/products/Link → Picture → Bộ Nội Thất Phòng Khách MOHO DALUMD.png",
        thumbs: ["/src/images/products/Link → Picture → Bộ Nội Thất Phòng Khách MOHO DALUMD.png"],
        descImg: "/src/images/products/Link → Picture → Bộ Nội Thất Phòng Khách MOHO DALUMD.png"
    },
    "koster-dining": {
        title: "Combo Phòng Ăn TLU KOSTER Màu Nâu",
        sku: "MSET_KOSTER_DINING",
        discount: "-31%",
        currentPrice: "8,490,000đ",
        oldPrice: "12,350,000đ",
        colorName: "Nâu Sẫm",
        colors: ["#5c4033"],
        size: "Bàn ăn W1400mm x D800mm kèm 4 ghế đơn bọc nệm",
        materials: ["Mặt bàn gỗ chống ẩm phủ Melamine chống trầy", "Khung ghế gỗ cao su bọc vải nỉ cao cấp"],
        descTitle: "Bộ Bàn Ăn KOSTER - Nơi Giữ Lửa Tổ Ấm Gia Đình",
        descText: "Các góc bàn được bo tròn an toàn cho nhà có trẻ nhỏ.",
        mainImg: "/src/images/products/Link → Picture → Combo Phòng Ăn MOHO KOSTER Màu Nâu.png",
        thumbs: ["/src/images/products/Link → Picture → Combo Phòng Ăn MOHO KOSTER Màu Nâu.png"],
        descImg: "/src/images/products/Link → Picture → Combo Phòng Ăn MOHO KOSTER Màu Nâu.png"
    },
    "vline-combo": {
        title: "Combo Giường Tủ Quần Áo VLINE V3",
        sku: "MSET_VLINE_BEDROOM",
        discount: "-14%",
        currentPrice: "18,990,000đ",
        oldPrice: "21,980,000đ",
        colorName: "Nâu Gỗ Đậm",
        colors: ["#5c4033", "#d2b48c"],
        size: "Giường ngủ 1m8x2m và Tủ quần áo 2 cánh đứng V3",
        materials: ["Gỗ tự nhiên đồng bộ kết cấu", "Phụ kiện kim khí giảm chấn chống rỉ sét"],
        descTitle: "Combo Phòng Ngủ VLINE V3 - Thiết Kế Đồng Bộ Toàn Diện",
        descText: "Giải pháp mua sắm trọn gói giúp căn phòng của bạn đạt điểm tuyệt đối về thẩm mỹ.",
        mainImg: "/src/images/products/Link → Picture → Combo Giường Tủ Quần Áo VLINE V3.png",
        thumbs: ["/src/images/products/Link → Picture → Combo Giường Tủ Quần Áo VLINE V3.png"],
        descImg: "/src/images/products/Link → Picture → Combo Giường Tủ Quần Áo VLINE V3.png"
    },
    "tu-dau-giuong-scarlet": {
        title: "Tủ Đầu Giường Gỗ Tấn Bì Cao Cấp SCARLET - TLU Signature",
        sku: "MNTST050_SCARLET",
        discount: "-17%",
        currentPrice: "4,990,000đ",
        oldPrice: "5,990,000đ",
        colorName: "Nâu Đậm Cherry",
        colors: ["#4a2c11"],
        size: "W550mm x D450mm x H500mm",
        materials: ["Gỗ sồi Mỹ nhập khẩu nguyên khối sơn PU phủ bóng cao cấp"],
        descTitle: "Táp Đầu Giường SCARLET - Điểm Nhấn Thượng Lưu Quý Phái",
        descText: "Thiết kế hộc kéo lượn chỉ phào mềm mại, tay nắm đồng đúc cổ điển mang đậm hơi thở hoàng gia.",
        mainImg: "/src/images/products/Link → Picture → Tủ Đầu Giường Gỗ Tần Bì Cao Cấp SCARLET - MOHO Signature.png",
        thumbs: ["/src/images/products/Link → Picture → Tủ Đầu Giường Gỗ Tần Bì Cao Cấp SCARLET - MOHO Signature.png"],
        descImg: "/src/images/products/Link → Picture → Tủ Đầu Giường Gỗ Tần Bì Cao Cấp SCARLET - MOHO Signature.png"
    },
    "combo-scarlet": {
        title: "Combo Phòng Ngủ SCARLET - TLU Signature",
        sku: "MSET_SCARLET_SIGNATURE",
        discount: "-15%",
        currentPrice: "21,990,000đ",
        oldPrice: "25,980,000đ",
        colorName: "Nâu Đậm Cherry",
        colors: ["#4a2c11"],
        size: "Bao gồm 1 giường ngủ bọc vải nỉ cao cấp và hệ táp đầu giường",
        materials: ["Gỗ tự nhiên kết hợp gỗ thông xẻ sấy chống mối mọt đạt tiêu chuẩn"],
        descTitle: "Bộ Phòng Ngủ SCARLET - Đẳng Cấp Không Gian Nghỉ Ngơi Quý Tộc",
        descText: "Nằm trong bộ sưu tập Signature giới hạn, SCARLET kiến tạo nên trải nghiệm thư thái tuyệt đối.",
        mainImg: "/src/images/products/Link → Picture → Combo Phòng Ngủ SCARLET - MOHO Signature.png",
        thumbs: ["/src/images/products/Link → Picture → Combo Phòng Ngủ SCARLET - MOHO Signature.png"],
        descImg: "/src/images/products/Link → Picture → Combo Phòng Ngủ SCARLET - MOHO Signature.png"
    },
    "giuong-scarlet-1m6": {
        title: "Giường Ngủ Bọc Vải 1m6 SCARLET - TLU Signature",
        sku: "MBDSCAR16_FAB",
        discount: "-15%",
        currentPrice: "17,990,000đ",
        oldPrice: "19,990,000đ",
        colorName: "Xám Sọc Caro",
        colors: ["#7f7f7f"],
        size: "W1600mm x L2000mm",
        materials: ["Vải dệt họa tiết cao cấp nhập khẩu, vạt giường bọc đệm êm ái"],
        descTitle: "Giường Ngủ SCARLET 1m6 - Sự Êm Ái Tinh Tế Cho Phòng Master",
        descText: "Khung giường chắc chắn, vạt tấm lót sàn chịu tải trọng tối đa, mang lại giấc ngủ sâu đúng nghĩa.",
        mainImg: "/src/images/products/Link → Picture → Giường Ngủ Bọc Vải 1m6 SCARLET - MOHO Signature.png",
        thumbs: ["/src/images/products/Link → Picture → Giường Ngủ Bọc Vải 1m6 SCARLET - MOHO Signature.png"],
        descImg: "/src/images/products/Link → Picture → Giường Ngủ Bọc Vải 1m6 SCARLET - MOHO Signature.png"
    },
    "bo-ban-an-plank": {
        title: "Bộ Bàn Ghế Ăn 4 Ghế Gỗ Tự Nhiên PLANK",
        sku: "MSET_PLANK_DINING",
        discount: "-27%",
        currentPrice: "15,590,000đ",
        oldPrice: "21,950,000đ",
        colorName: "Nâu Gỗ Tự Nhiên",
        colors: ["#5c4033", "#d2b48c"],
        size: "Bàn ăn dài 1m4 kèm 4 ghế tựa mộc",
        materials: ["100% Gỗ tràm và cao su tự nhiên sơn phủ chống trầy xước nước"],
        descTitle: "Bộ Bàn Ăn PLANK - Tối Giản, Mộc Mạc Đến Từ Thiên Nhiên",
        descText: "Thiết kế mặt bàn nguyên tấm vuông vức cá tính, chân bàn khối chịu lực cao, phù hợp hoàn hảo cho căn hộ chung cư ấm cúng.",
        mainImg: "/src/images/products/Link → Picture → Bộ Bàn Ghế Ăn 4 Ghế Gỗ Tự Nhiên PLANK.png",
        thumbs: ["/src/images/products/Link → Picture → Bộ Bàn Ghế Ăn 4 Ghế Gỗ Tự Nhiên PLANK.png"],
        descImg: "/src/images/products/Link → Picture → Bộ Bàn Ghế Ăn 4 Ghế Gỗ Tự Nhiên PLANK.png"
    }
};